### Obtener todos los jugadores
GET http://localhost:3000/api/jugadores
Content-Type: application/json


### Crear un nuevo jugador
POST http://localhost:3000/api/jugadores
Content-Type: application/json

{
  "nombre": "Geronimo",
  "apellido": "Negri",
  "dni": "46494676",
  "email": "geroNegri@gmail.com",
  "fechaNacimiento": "2005-05-10",
  "contraseña": "juanchon",
  "posicion": "Delantero",
  "equipo": 1
}


### Obtener un jugador por ID
GET http://localhost:3000/api/jugadores/1
Content-Type: application/json


### Actualizar un jugador existente
PUT http://localhost:3000/api/jugadores/1
Content-Type: application/json

{
  "nombre": "Lucas",
  "apellido": "Gómez",
  "dni": "40256123",
  "email": "lucas.gomez@example.com",
  "fecha_nacimiento": "2000-08-15",
  "contraseña": "nuevoPass123",
  "posicion": "Mediocampista",
  "equipo_id": 1
}


### Eliminar un jugador
DELETE http://localhost:3000/api/jugadores/1
Content-Type: application/json