### Obtener todos los jugadores
GET http://localhost:3000/api/jugadores
Content-Type: application/json


### Crear un nuevo jugador
POST http://localhost:3000/api/jugadores
Content-Type: application/json

{
  "nombre": "Ramon",
  "apellido": "Alvarez",
  "dni": "42293153",
  "email": "ramons@gmail.com",
  "fechaNacimiento": "2003-09-25",
  "contraseña": "ramon",
  "posicion": "Mediocampista",
  "equipo": 2,
  "esCapitan": true
}



### Obtener un jugador por ID
GET http://localhost:3000/api/jugadores/1
Content-Type: application/json


### Actualizar un jugador existente
PUT http://localhost:3000/api/jugadores/6
Content-Type: application/json

{
  "posicion": "Defensor"
}


### Eliminar un jugador
DELETE http://localhost:3000/api/jugadores/8
Content-Type: application/json