### Obtener todos los torneos
GET http://localhost:3000/api/torneo
Content-Type: application/json


### Obtener un torneo por ID
GET http://localhost:3000/api/torneo/1
Content-Type: application/json


### Crear un nuevo torneo
POST http://localhost:3000/api/torneo
Content-Type: application/json

{
  "nombreTorneo": "Torneo mayores Calusura 2025",
  "fechaInicio": "2025-07-01",
  "fechaFin": "2025-12-05",
  "estado": "activo",
  "adminTorneo": 3
}


### Actualizar un torneo existente
PUT http://localhost:3000/api/torneo/1
Content-Type: application/json

{
  "nombre": "Torneo Apertura 2025 - Actualizado",
  "fechaInicio": "2025-03-10",
  "fechaFin": "2025-07-20",
  "estado": "en progreso",
  "adminTorneo": 3
}


### Eliminar un torneo por ID
DELETE http://localhost:3000/api/torneo/1
Content-Type: application/json