### obtener todos los characters
GET http://localhost:3000/api/characters

### obtener un character
GET http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### crear un nuevo character
POST http://localhost:3000/api/characters
Content-Type: application/json

{
    "name": "Atila",                               
    "level": 10,
    "attack": 100,
    "items": ["bow", "arrow"]
}

### modificar un character (put idempotente (modif completas), en patch no necesario(modif parciales))
PUT http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "name": "Anakin",                               
    "level": 12,
    "attack": 150,
    "items": ["Lightsaber", "Death Star"]
}


### modificar parcialmente un character  (sirve para modificaciones incrementales tambien, como subir un nivel o agregar un item)
PATCH  http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "name": "Anakin",                               
    "attack": 150,
    "items": ["Lightsaber", "Reloj"]
}

###borrar un character
DELETE http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad 