### Obtener todos los árbitros
GET http://localhost:3000/api/arbitros
Content-Type: application/json


### Crear un nuevo árbitro
POST http://localhost:3000/api/arbitros
Content-Type: application/json

{
  "nombre": "Matheu",
  "apellido": "Laoz",
  "nro_matricula": "18332",
  "email": "mLaoz@gmail.com"
}


### Obtener un árbitro por ID
GET http://localhost:3000/api/arbitros/2
Content-Type: application/json


### Actualizar un árbitro existente
PUT http://localhost:3000/api/arbitros/1
Content-Type: application/json

{
  "nombre": "Carlos",
  "apellido": "Pérez",
  "nro_matricula": "12384",
  "email": "carlos.perez@gmail.com"
}


### Eliminar un árbitro
DELETE http://localhost:3000/api/arbitros/1
Content-Type: application/json